### ISSUE TITLE
NBC Sports channels

### ISSUE THREAD

**Issue by 0845** [Jasmeet181/mediaportal-us-logos#1]
Hello  

Possible to get logos for the below channels

NBC Sports California Plus
NBC Sports Bay Area Plus

**Comment by Jasmeet181** [comment]
In the future it would be helpful to include an image with the logo if they need adding or updating, for example I used the images in these tweets https://twitter.com/NBCSSharks/status/992626852178022400 and https://twitter.com/SFGiants/status/856669097957900288

**Comment by 0845** [comment]
Will do thanks :-)
