### ISSUE TITLE
Channel Logo

### ISSUE THREAD

**Issue by 0845** [Jasmeet181/mediaportal-us-logos#2]
Possible to add the Logo for below channels

Spectrum SportsNet Lakers

https://spectrumsportsnet.com/lakers

MGM Sci-Fi

The Film Detective 

TUTV
https://templetv.net/watch-live/

**Comment by Jasmeet181** [comment]
MGM Sci-Fi and The Film Detective appear to be a part of streaming services/apps rather than TV channels, can you confirm?

**Comment by 0845** [comment]
yes you are actually right.

**Comment by 0845** [comment]
Also if you can get hold of the logos for this will be great

Leominster TV Public
Leominster TV Government
Leominster TV Educational
Website: http://www.leominster.tv/

Greensboro Television Network (GTN)
https://www.greensboro-nc.gov/departments/communications-marketing/greensboro-television-network-gtn

**Comment by Jasmeet181** [comment]
Can you post an export file containing these channels?
