### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by chloejules** [Jasmeet181/mediaportal-us-logos#3]
Hi

Do you have the below logos?

CW 5 (KESQ-DT8) Palm Springs
CW 8 (KPAX) Missoula
CW 17 (WCWJ) Jacksonville
CW 17 (WCWJ) Jacksonville
CW 13 (KYLX) Laredo
CW 8 (KNOE-DT2) Monroe-El Dorado
CW 46 (WXCW) Fort Myers
 CW 18 (WCCB) Charlotte
CW 22 (WBMM) Montgomery
CW 69 (WUPA) Atlanta

MAX Latino
https://www.holstonconnect.com/sites/holstonconnect/files/2019-04/Cinemax.png

Fox Sports Arizona Plus 
Fox Sports Ohio Plus
Fox Sports Indiana Plus
Fox Sports Oklahoma Plus
Fox Sports San Diego Plus
PBS 13 (WNETDT) NewYork

**Comment by Jasmeet181** [comment]
> Do you have the below logos?

Other than WNET, I don't think so, use Find file or download the repository and see.

> MAX Latino
> https://www.holstonconnect.com/sites/holstonconnect/files/2019-04/Cinemax.png

I have Cinemáx, "Max Latino – which dropped its distinct branding and was renamed Cinemáx on April 1, **2015**" - [Wikipedia](https://en.wikipedia.org/wiki/Cinemax#Background).

**Comment by chloejules** [comment]
ok thanks
